---
services:
  anon:
    build: .
    image: anon:local
    container_name: anon
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=prod
    volumes:
      - anon_temp:/app/temp
      - anon_models:/app/models
      - anon_logs:/app/logs
    networks:
      - anon

volumes:
  anon_temp:
  anon_models:
  anon_logs:

networks:
  anon:
    name: anon
    driver: bridge
